# Generated by Django 5.1.3 on 2024-11-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('dados', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
